DROP TABLE IF EXISTS REIMBURSEMENT_TYPE CASCADE;
CREATE TABLE REIMBURSEMENT_TYPE(
	R_TYPE_ID SERIAL PRIMARY KEY,
	R_TYPE VARCHAR(250) NOT NULL
);

CREATE TABLE IF EXISTS USR CASCADE;
CREATE TABLE USR(
	USER_ID SERIAL PRIMARY KEY,
	EMAIL VARCHAR(250) NOT NULL,
	PWD VARCHAR(250) NOT NULL,
	FIRSTNAME VARCHAR(250) NOT NULL,
	LASTNAME VARCHAR(250) NOT NULL,
	ROLL NUMERIC,
	APPROVED NUMERIC
);

CREATE TABLE IF EXISTS REIMBURSEMENTS CASCADE;
CREATE TABLE REIMBURSEMENTS(
	R_ID SERIAL PRIMARY KEY,
	AUTHOR INTEGER NOT NULL,
	AMOUNT NUMERIC,
	SUBMIT_DATE VARCHAR(100),
	RESOLVE_DATE VARCHAR(100),
	R_TYPE INTEGER,
	R_DESC VARCHAR(500),
	R_STATUS INTEGER,
	
	FOREIGN KEY (AUTHOR) REFERENCES USR(USER_ID),
	FOREIGN KEY (R_TYPE) REFERENCES REIMBURSEMENT_TYPE(R_TYPE_ID)
);

